### ISSUE TITLE
Unnamed reverse relationships cannot be used in sealed prefetches

### ISSUE THREAD

**Issue by fish-face** [charettes/django-seal#38]
```python3
class Library(Model):
    pass
class Book(Model):
    library = ForeignKey(Library)

libraries = Library.objects.prefetch_related('book_set').seal()
```
Fails with `FieldDoesNotExist` on `book_set`. If you set the `related_name` of `library` to `book_set` it works fine. (All relationships in the test data have related names set explicitly.)

**Comment by charettes** [comment]
This was fixed by #41.

**Comment by fish-face** [comment]
Just to confirm this resolved the problem we were seeing.

**Comment by charettes** [comment]
@fish-face thanks for confirming. I'll give a shot at solving #39 later this week and plan on releasing 1.2 with the corrective right after.

Is there anything else that surprised you about the current interface and how it was documented/implemented?

**Comment by fish-face** [comment]
We were hoping to have a mixin class, however appreciate this is annoying
with django's metaclassing, and with only one method, which is not on the
base class, there seems to be no issue here.

I think, but have not confirmed, that there would be a problem with a model
which uses a default manager not called `objects`.

Beyond that we're still testing :)

On a general note I first encountered similar functionality with
sqlalchemy's `raiseload` strategy. So the interface is very different but I
don't know what can be done about that.

The ability to say "I want any lazy load in this view to be an
error/warning" without going through each query would be useful to us, I
think. It would be a very different way of getting the seal functionality
perhaps; you might have to monkey patch the base model class (though not
having to explicitly inherit from `SealableModel` would be nice).

I'll let you know if we find any concrete surprises or bugs!

**Comment by charettes** [comment]
@fish-face thanks for your feedback!

> We were hoping to have a mixin class, however appreciate this is annoying
with django's metaclassing, and with only one method, which is not on the
base class, there seems to be no issue here.

yeah it's kind of tricking because of all the meta programming involved.

> I think, but have not confirmed, that there would be a problem with a model
which uses a default manager not called `objects`.

Feel free to file an issue if that happens to be the case.

> The ability to say "I want any lazy load in this view to be an error/warning" without going through each query would be useful to us, I think. 

Given you use CBVs it should be relatively easy to implement by defining a mixing that override methods in charge of returning querysets to call `.seal()` on `super().method()`.

> you might have to monkey patch the base model class (though not
having to explicitly inherit from `SealableModel` would be nice).

I'd like to get to a point where we can make `seal.models.make_model_sealable` a public API. Right now it should be working pretty well except that it doesn't add the `.seal()` method on the model class. Queryset sealing should all be working though.
